메인페이지 아이콘 버튼 구현 #13
likelion-reactproject-lab12/together pull request #34
Opened 2023-03-14 16:40 UTC by sykang013

## ✨ 구현 기능 명세
- globalStyle에 a태그 커서 포인터 설정
- sprites.svg 추가 및 수정("simbol" -> "symbol-logo")
- sprites.svg 아이콘을 불러오는 함수 작업 및 응용
- 아이콘 버튼 브라우저 너비에 따른 반응형 구현

## 🎁 PR Point
- 일단은 버튼 UI만 구현했는데, 코드리뷰겸 해서 올려봅니다! 
- 질문 사항들은 해당 코드 부분에 코멘트로 달아두겠습니다.

## 😊 etc
-

2023-03-14 16:46 UTC, sykang013 reviewed
- 작업하면서 개인적으로 든 의문들을 코멘트로 남기니 한번 봐주시면 감사하겠습니다.
- 그 밖에 계단형으로 뚝뚝 끊기지 않고 부드럽게 변환되도록 개선이 필요합니다.

2023-03-14 16:46 UTC, sykang013 commented on src/components/landing/IconButton.jsx
> +  const Sprite = ({ id, viewBox }) => (
- id와 viewBox 값을 인자로 받아 원하는 아이콘을 불러오는 컴포넌트 입니다만, 이렇게 컴포넌트 안의 컴포넌트로 사용할지, getColor나 rem처럼 유틸함수로 따로 빼는게 좋을지 의견주시면 감사하겠습니다.

2023-03-15 00:48 UTC, senasoon requested changes

2023-03-15 00:48 UTC, senasoon commented on src/assets/sprites.svg
sprite.svg로 변경되면 좋을 것 같습니다!

2023-03-15 00:48 UTC, senasoon commented on src/components/landing/IconButton.jsx
> +  const Sprite = ({ id, viewBox }) => (
함수 컴포넌트 안에서 styled-components가 사용되고 있는데 저렇게 되면 컴포넌트가 렌더링 될 때마다 styled-components를 다시 정의해야 하기 때문에 애플리케이션 속도에 영향을 미친다고 합니다! 수정이 필요해보입니다.

2023-03-15 00:48 UTC, senasoon commented on src/components/landing/IconButton.jsx
> +  const Sprite = ({ id, viewBox }) => (
해당 내용을 sprite 컴포넌트로 분리하는게 좋을 것 같습니다! 사용하기에도 더 편리할 것 같아요!

2023-03-15 00:48 UTC, senasoon commented on src/pages/MainPage.jsx
테스트 목적이고 메인페이지와 관련되지 않은 작업이라면 변경사항에 포함되지 않는게 좋을 것 같아요!

2023-03-15 09:00 UTC, closed without merging