Develop
likelion-reactproject-lab12/together pull request #54
Opened 2023-03-20 00:22 UTC by guahyoung

## ✨ 구현 기능 명세
- 팝업 닫기 버튼 
- 팝업 오늘 하루 보지 않기 

## 🎁 PR Point
-

## 😊 etc
-

2023-03-20 00:41 UTC, senasoon requested changes
props는 읽기 전용이기 때문에 자식에서 부모의 상태를 바꾸는 것은 안된다고 알고 있습니다. 그렇기 때문에 setState를 전달하는게 아니라 상태를 변경하는 함수를 전달하는 것으로 알고 있어요! 

```
const togglePopUpState = () => {
 setPopup((popup)=> !popup)
}
```
위와 같은 함수를 부모에서 자식으로 전달해서 부모에서 함수가 작동할 수 있도록 해야 할 것 같습니다! Onclose(e)는 어떤 상황일까요? 위 함수는 상태를 반대로 바꿔주는 역할을 합니다!

2023-03-20 01:07 UTC, imironjin commented on src/components/popup/Popup.jsx
> +      if (VisitedBeforeDate === VisitedNowDate) {
현재 시간과 전 시간을 비교해서 removeItem하는 것처럼 보이는데요. 86번째 줄에서 setItem한 expiryDate를 활용해서 현재 시간과 비교해서 **시간을 넘었다면** removeItem해야 하지 않을까요 ?? 그리고 이 과정에서 형 변환도 필요한 것 같습니다
https://hianna.tistory.com/698
https://www.sohamkamani.com/javascript/localstorage-with-ttl-expiry/
참고하시면 좋을만한 링크 남겨둡니다.

2023-03-21 02:00 UTC, guahyoung commented on src/components/popup/Popup.jsx
> +      if (VisitedBeforeDate === VisitedNowDate) {
수정 했습니다.

2023-03-21 02:04 UTC, senasoon commented on src/pages/MainPage.jsx
> +          }}
onClose로 변경되어야 할 것 같아요 camelCase로 부탁드립니다. 그리고 인수를 전달하지 않아서 `onClose={handleCloseModal}`로 작성되면 좋을 것 같아요

2023-03-21 02:08 UTC, senasoon commented on src/components/popup/Popup.jsx
> +      }
현재 Onclose는 handleCloseModal 함수이고 인수를 받고있지 않는데 OnClose(true)와 OnClose(false)로 되어 있어서 수정이 필요해보입니다!

2023-03-21 02:10 UTC, senasoon commented on src/components/popup/Popup.jsx
> +  };
이렇게 함수를 또 생성하지 않고 닫을 때는 Onclose()로 하면되지 않을까요? 닫기 버튼 onClick에 OnClose를 할당하면 될 것 같습니다!

2023-03-21 02:11 UTC, senasoon commented on src/components/popup/Popup.jsx
> +  const { OnClose } = props;
const Popup = ({OnClose}) => {
위와 같이 수정하시면 한줄로 가능합니다!

2023-03-21 02:16 UTC, guahyoung commented on src/components/popup/Popup.jsx
> +      OnClose(e);
if(OnClose) OnClose(e)는 onClose 함수가 정의되어 있고, truthy한지 확인해서 오늘 하루 보지 않기 버튼이 클릭 될 때 전달 된 함수를 호출해서 팝업을 닫는 역할을 합니다.

2023-03-21 02:20 UTC, senasoon commented on src/components/popup/Popup.jsx
> +      OnClose(e);
if문을 빼고 onClose를 마지막에 onClose()로 작성해도 오류가 나나요?

2023-03-21 02:21 UTC, guahyoung commented on src/components/popup/Popup.jsx
> +      OnClose(e);
네 오류 발생합니다..

2023-03-21 02:31 UTC, guahyoung commented on src/components/popup/Popup.jsx
> +  const { OnClose } = props;
변경 했습니다.

2023-03-21 02:31 UTC, guahyoung commented on src/components/popup/Popup.jsx
> +  };
변경 했습니다.

2023-03-21 02:31 UTC, guahyoung commented on src/pages/MainPage.jsx
> +          }}
변경 했습니다.

2023-03-21 05:26 UTC, imironjin approved these changes
고생하셨습니다.

2023-03-21 05:43 UTC, sykang013 approved these changes
LGTM! 감동적인 코드리뷰였습니다

2023-03-21 05:44 UTC, kyungseob7 approved these changes
고생하셨습니다!

2023-03-21 06:02 UTC, senasoon approved these changes

2023-03-21 06:02 UTC, merged